spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:${CONFIG_DEFAULT_ZONE:http://127.0.0.1:8888}"
  cloud:
    config:
      username: user
      password: Config@123