version: "3.8"

networks:
  backend-app-network:
    driver: bridge

services:
  config-service:
    container_name: config-service
    image: config_service:latest
    restart: always
    build:
      context: ./config-service
      dockerfile: Dockerfile
    environment:
      - EUREKA_DEFAULT_ZONE=http://registry-service:8761/eureka/
    ports:
      - "8888:8888"
    healthcheck:
      test: curl -f http://localhost:8888/login || exit 1
      interval: 5s
      timeout: 15s
      retries: 3
      start_period: 20s
    networks:
      - backend-app-network
  registry-service:
    container_name: registry-service
    image: registry_service:latest
    restart: always
    build:
      context: ./registry-service
      dockerfile: Dockerfile
    environment:
      - EUREKA_DEFAULT_ZONE=http://registry-service:8761/eureka/
      - CONFIG_SERVER_URL=http://config-service:8888
    ports:
      - "8761:8761"
    healthcheck:
      test: curl -f http://localhost:8761 || exit 1
      interval: 5s
      timeout: 15s
      retries: 3
      start_period: 20s
    networks:
      - backend-app-network
    depends_on:
      config-service:
        condition: service_healthy
  gateway-service:
    container_name: gateway-service
    image: gateway_service:latest
    restart: always
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    environment:
      - EUREKA_DEFAULT_ZONE=http://registry-service:8761/eureka/
      - CONFIG_SERVER_URL=http://config-service:8888
    ports:
      - "8080:8080"
    networks:
      - backend-app-network
    depends_on:
      config-service:
        condition: service_healthy
      registry-service:
        condition: service_healthy
  auth-service:
    container_name: auth-service
    image: auth_service:latest
    restart: unless-stopped
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    environment:
      - EUREKA_DEFAULT_ZONE=http://registry-service:8761/eureka/
      - CONFIG_SERVER_URL=http://config-service:8888
    ports:
      - "8081:8081"
    networks:
      - backend-app-network
    depends_on:
      config-service:
        condition: service_healthy
      registry-service:
        condition: service_healthy
  account-service:
    container_name: account-service
    image: account_service:latest
    restart: on-failure
    build:
      context: ./account-service
      dockerfile: Dockerfile
    environment:
      - EUREKA_DEFAULT_ZONE=http://registry-service:8761/eureka/
      - CONFIG_SERVER_URL=http://config-service:8888
    ports:
      - "8082:8082"
    networks:
      - backend-app-network
    depends_on:
      config-service:
        condition: service_healthy
      registry-service:
        condition: service_healthy